// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"cloud.google.com/go/firestore"
	"context"
	"local.packages/src"
	"local.packages/task"
	"local.packages/voice"
)

// Injectors from wire.go:

func InitializeCLI(client *firestore.Client, ctx context.Context) (*src.CLI, error) {
	repositoryInterface := Voice.NewRepository(client, ctx)
	serviceInterface := Voice.NewService(repositoryInterface)
	voiceTask := Task.NewVoiceTask(serviceInterface)
	cli := src.NewCLI(voiceTask)
	return cli, nil
}
